# Generated by Django 3.2.5 on 2021-07-28 00:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("bookmarker", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="EmailConfirmationToken",
            fields=[
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        primary_key=True,
                        serialize=False,
                        to="bookmarker.user",
                    ),
                ),
                ("token", models.CharField(max_length=100)),
            ],
        ),
    ]
