# Generated by Django 3.2.5 on 2021-08-02 12:46

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("bookmarker", "0003_bookmark_list"),
    ]

    operations = [
        migrations.AlterField(
            model_name="emailconfirmationtoken",
            name="user",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                primary_key=True,
                related_name="email_confirm_token",
                serialize=False,
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
